In [17]:
from modulos.data_load import load
from sklearn.neural_network import MLPRegressor
import pandas as pd

In [32]:
df = load('AAVEBTC')
df

,unix,date,symbol,open,high,low,close,Volume AAVE,Volume BTC,buyTakerAmount,buyTakerQuantity,tradeCount,weightedAverage
41405,1602288000000,2020-10-10 00:00:00,AAVE/BTC,0.003800,0.009801,0.003800,0.004801,0.001804,0.338493,0.0,0.0,0,0.005331
41404,1602352800000,2020-10-10 18:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000380,0.100026,0.0,0.0,0,0.000000
41403,1602356400000,2020-10-10 19:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
41402,1602360000000,2020-10-10 20:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
41401,1602363600000,2020-10-10 21:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1751400000000,2025-07-01 20:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
3,1751403600000,2025-07-01 21:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
2,1751407200000,2025-07-01 22:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
1,1751410800000,2025-07-01 23:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
0,1751414400000,2025-07-02 00:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398

In [33]:
predictors = [ 'unix', 'tradeCount', 'weightedAverage' ]
outcome = 'close'

X = df[predictors]
y = df[outcome]

In [34]:
regg = MLPRegressor(hidden_layer_sizes=(20, 10), activation='logistic', max_iter=1000)
regg.fit(X, y)
regg.predict(X)

array([0.00342768, 0.00342768, 0.00342768, ..., 0.00342768, 0.00342768,
       0.00342768], shape=(41406,))

In [55]:
dff = df
dff['PREDICTED'] = regg.predict(X)
dff

,unix,date,symbol,open,high,low,close,Volume AAVE,Volume BTC,buyTakerAmount,buyTakerQuantity,tradeCount,weightedAverage,PREDICTED
41405,1602288000000,2020-10-10 00:00:00,AAVE/BTC,0.003800,0.009801,0.003800,0.004801,0.001804,0.338493,0.0,0.0,0,0.005331,0.003428
41404,1602352800000,2020-10-10 18:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000380,0.100026,0.0,0.0,0,0.000000,0.003428
41403,1602356400000,2020-10-10 19:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.003428
41402,1602360000000,2020-10-10 20:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.003428
41401,1602363600000,2020-10-10 21:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.003428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1751400000000,2025-07-01 20:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003428
3,1751403600000,2025-07-01 21:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003428
2,1751407200000,2025-07-01 22:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003428
1,1751410800000,2025-07-01 23:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003428
0,1751414400000,2025-07-02 00:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.003428

In [56]:
dff = dff[[ 'symbol', 'date', 'close', 'PREDICTED' ]].rename(columns={ 'close': 'FECHAMENTO REAL' })
dff['ERRO'] = dff[['FECHAMENTO REAL', 'PREDICTED']].apply(lambda row: abs(row['FECHAMENTO REAL'] - row['PREDICTED']), axis=1)
dff

         symbol                date  FECHAMENTO REAL  PREDICTED      ERRO
41405  AAVE/BTC 2020-10-10 00:00:00         0.004801   0.003428  0.001373
41404  AAVE/BTC 2020-10-10 18:00:00         0.003800   0.003428  0.000372
41403  AAVE/BTC 2020-10-10 19:00:00         0.003800   0.003428  0.000372
41402  AAVE/BTC 2020-10-10 20:00:00         0.003800   0.003428  0.000372
41401  AAVE/BTC 2020-10-10 21:00:00         0.003800   0.003428  0.000372
...         ...                 ...              ...        ...       ...
4      AAVE/BTC 2025-07-01 20:00:00         0.002398   0.003428  0.001030
3      AAVE/BTC 2025-07-01 21:00:00         0.002398   0.003428  0.001030
2      AAVE/BTC 2025-07-01 22:00:00         0.002398   0.003428  0.001030
1      AAVE/BTC 2025-07-01 23:00:00         0.002398   0.003428  0.001030
0      AAVE/BTC 2025-07-02 00:00:00         0.002398   0.003428  0.001030

[41406 rows x 5 columns]

In [57]:
dff[dff['ERRO'] == dff['ERRO'].max()]

         symbol                date  FECHAMENTO REAL  PREDICTED      ERRO
36111  AAVE/BTC 2021-05-19 07:00:00         0.015346   0.003428  0.011918

In [58]:
dff[dff['ERRO'] == dff['ERRO'].min()]

         symbol                date  FECHAMENTO REAL  PREDICTED          ERRO
26125  AAVE/BTC 2022-07-09 09:00:00         0.003428   0.003428  1.311437e-07