In [117]:
from modulos.data_load import load
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [118]:
df = load('AAVEBTC')
df

,unix,date,symbol,open,high,low,close,Volume AAVE,Volume BTC,buyTakerAmount,buyTakerQuantity,tradeCount,weightedAverage
41405,1602288000000,2020-10-10 00:00:00,AAVE/BTC,0.003800,0.009801,0.003800,0.004801,0.001804,0.338493,0.0,0.0,0,0.005331
41404,1602352800000,2020-10-10 18:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000380,0.100026,0.0,0.0,0,0.000000
41403,1602356400000,2020-10-10 19:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
41402,1602360000000,2020-10-10 20:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
41401,1602363600000,2020-10-10 21:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1751400000000,2025-07-01 20:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
3,1751403600000,2025-07-01 21:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
2,1751407200000,2025-07-01 22:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
1,1751410800000,2025-07-01 23:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398
0,1751414400000,2025-07-02 00:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398

In [119]:
predictors = [ 'unix', 'high', 'low', 'open' ]
outcome = 'close'

X = df[predictors]
y = df[outcome]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.73337544,  2.81173427,  0.057891  ,  0.04552922],
       [-1.73186963,  0.03510084,  0.057891  ,  0.04552922],
       [-1.73178597,  0.03510084,  0.057891  ,  0.04552922],
       ...,
       [ 1.73183488, -0.61365809, -0.60681376, -0.61046133],
       [ 1.73191853, -0.61365809, -0.60681376, -0.61046133],
       [ 1.73200219, -0.61365809, -0.60681376, -0.61046133]],
      shape=(41406, 4))

In [120]:
regg = MLPRegressor(hidden_layer_sizes=(200,100, 10), activation='relu', max_iter=100, random_state=1)
regg.fit(X_scaled, y)
regg.predict(X_scaled)

array([0.00524293, 0.0049126 , 0.00491128, ..., 0.00217605, 0.00217612,
       0.0021762 ], shape=(41406,))

In [122]:
len(set(regg.predict(X_scaled)))

41406

In [123]:
dff = df
dff['PREDICTED'] = regg.predict(X_scaled)
dff

,unix,date,symbol,open,high,low,close,Volume AAVE,Volume BTC,buyTakerAmount,buyTakerQuantity,tradeCount,weightedAverage,PREDICTED
41405,1602288000000,2020-10-10 00:00:00,AAVE/BTC,0.003800,0.009801,0.003800,0.004801,0.001804,0.338493,0.0,0.0,0,0.005331,0.005243
41404,1602352800000,2020-10-10 18:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000380,0.100026,0.0,0.0,0,0.000000,0.004913
41403,1602356400000,2020-10-10 19:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.004911
41402,1602360000000,2020-10-10 20:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.004910
41401,1602363600000,2020-10-10 21:00:00,AAVE/BTC,0.003800,0.003800,0.003800,0.003800,0.000000,0.000000,0.0,0.0,0,0.000000,0.004909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1751400000000,2025-07-01 20:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.002176
3,1751403600000,2025-07-01 21:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.002176
2,1751407200000,2025-07-01 22:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.002176
1,1751410800000,2025-07-01 23:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.002176
0,1751414400000,2025-07-02 00:00:00,AAVE/BTC,0.002398,0.002398,0.002398,0.002398,0.000000,0.000000,0.0,0.0,0,0.002398,0.002176

In [124]:
dff = dff[[ 'symbol', 'date', 'close', 'PREDICTED' ]].rename(columns={ 'close': 'FECHAMENTO REAL' })
dff['ERRO'] = dff[['FECHAMENTO REAL', 'PREDICTED']].apply(lambda row: abs(row['FECHAMENTO REAL'] - row['PREDICTED']), axis=1)
dff

         symbol                date  FECHAMENTO REAL  PREDICTED      ERRO
41405  AAVE/BTC 2020-10-10 00:00:00         0.004801   0.005243  0.000442
41404  AAVE/BTC 2020-10-10 18:00:00         0.003800   0.004913  0.001113
41403  AAVE/BTC 2020-10-10 19:00:00         0.003800   0.004911  0.001111
41402  AAVE/BTC 2020-10-10 20:00:00         0.003800   0.004910  0.001110
41401  AAVE/BTC 2020-10-10 21:00:00         0.003800   0.004909  0.001109
...         ...                 ...              ...        ...       ...
4      AAVE/BTC 2025-07-01 20:00:00         0.002398   0.002176  0.000222
3      AAVE/BTC 2025-07-01 21:00:00         0.002398   0.002176  0.000222
2      AAVE/BTC 2025-07-01 22:00:00         0.002398   0.002176  0.000222
1      AAVE/BTC 2025-07-01 23:00:00         0.002398   0.002176  0.000222
0      AAVE/BTC 2025-07-02 00:00:00         0.002398   0.002176  0.000222

[41406 rows x 5 columns]

In [125]:
dff[dff['ERRO'] == dff['ERRO'].max()]

         symbol                date  FECHAMENTO REAL  PREDICTED      ERRO
31337  AAVE/BTC 2021-12-04 05:00:00         0.003883   0.018132  0.014249

In [126]:
dff[dff['ERRO'] == dff['ERRO'].min()]

        symbol                date  FECHAMENTO REAL  PREDICTED          ERRO
3899  AAVE/BTC 2025-01-20 13:00:00         0.003292   0.003292  8.618348e-08

In [128]:
dff.loc[3899]['FECHAMENTO REAL']

np.float64(0.003292)

In [129]:
dff.loc[3899]['PREDICTED']

np.float64(0.003292086183476317)

In [131]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'